# Run default test plan in iPhone 16 Simulator

name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
    test:
      runs-on: macos-15

      steps:
      - name: Checkout repo
        uses: actions/checkout@v4
#     - name: Resolve Swift packages
#       run: swift package resolve
      - name: Test iPhone 16 Simulator
        run: xcodebuild test -workspace Thunderbird.xcworkspace -scheme ThunderbirdTests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 16'
