# Run tests in iPhone 16 Simulator

name: Thunderbird Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
    test:
      runs-on: macos-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
#       - name: Resolve Swift packages
#         run: swift package resolve
        - name: Run tests in iPhone 16 Simulator
          run: xcodebuild test -workspace Thunderbird.xcworkspace -scheme ThunderbirdTests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 16'
