# Run default test plan in iPhone 16 Simulator against iOS 18

name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
    test:
      runs-on: macos-15

      steps:
      - name: Checkout repo
        uses: actions/checkout@v4
#     - name: Resolve Swift packages
#       run: swift package resolve
      - name: Test Any iOS Simulator Device (iOS 18)
        run: xcodebuild test -workspace Thunderbird.xcworkspace -scheme ThunderbirdTests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=Any iOS Simulator Device,OS=18.0'
