# Run tests and analyze builds in iPhone 16 Simulator

name: Xcode Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
    test:
      runs-on: macos-15

      steps:
        - name: Checkout repository
          uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        - name: Resolve package dependencies
          run: xcodebuild -resolvePackageDependencies -workspace Thunderbird.xcworkspace -scheme Thunderbird
        - name: Build and analyze
          run: xcodebuild clean build analyze -workspace Thunderbird.xcworkspace -scheme Thunderbird -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 16'
        - name: Run tests in iPhone 16 Simulator
          run: xcodebuild test -workspace Thunderbird.xcworkspace -scheme ThunderbirdTests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 16'
